//
//  TTLStyle.h
//  TapTalkLive
//
//  Created by Dominic Vedericho on 18/01/20.
//  Copyright © 2020 taptalk.io. All rights reserved.
//

#ifndef TTLStyle_h
#define TTLStyle_h

#pragma mark - Font Typeface / Font Family
//Font
#define TTL_FONT_FAMILY_ITALIC @"DMSans-Italic"
#define TTL_FONT_FAMILY_REGULAR @"PTRootUI-Regular"
#define TTL_FONT_FAMILY_MEDIUM @"PTRootUI-Medium"
#define TTL_FONT_FAMILY_BOLD @"PTRootUI-Bold"

#pragma mark - Default Color
//Default Color
#define TTL_COLOR_PRIMARY_EXTRA_LIGHT @"FFA045"
#define TTL_COLOR_PRIMARY_LIGHT @"FF9833"
#define TTL_COLOR_PRIMARY @"FF7E00"
#define TTL_COLOR_PRIMARY_DARK @"E87200"
#define TTL_COLOR_SUCCESS @"7EC82A"
#define TTL_COLOR_ERROR @"FF3F57"
#define TTL_COLOR_TEXT_LIGHT @"FFFFFF"
#define TTL_COLOR_TEXT_MEDIUM @"9B9B9B"
#define TTL_COLOR_TEXT_DARK @"191919"
#define TTL_COLOR_ICON_PRIMARY @"FF7E00"
#define TTL_COLOR_ICON_WHITE @"FFFFFF"
#define TTL_COLOR_ICON_GRAY @"9B9B9B"
#define TTL_COLOR_ICON_SUCCESS @"7EC82A"
#define TTL_COLOR_ICON_ERROR @"FF3F57"

#pragma mark - Default Avatar Background Color
//Default Color
#define TTL_AVATAR_BACKGROUND_COLOR_1 @"F99181"
#define TTL_AVATAR_BACKGROUND_COLOR_2 @"A914DB"
#define TTL_AVATAR_BACKGROUND_COLOR_3 @"F26046"
#define TTL_AVATAR_BACKGROUND_COLOR_4 @"FB76AB"
#define TTL_AVATAR_BACKGROUND_COLOR_5 @"C4C9D1"
#define TTL_AVATAR_BACKGROUND_COLOR_6 @"4239BE"
#define TTL_AVATAR_BACKGROUND_COLOR_7 @"9C89F1"
#define TTL_AVATAR_BACKGROUND_COLOR_8 @"F4C22C"

#pragma mark - Component Color
//Component Color
#pragma mark Navigation Bar
//NavigationBar
#define TTL_DEFAULT_NAVIGATION_BAR_BACKGROUND_COLOR @"FFFFFF"
#define TTL_DEFAULT_BACKGROUND_COLOR @"F3F3F3"

#pragma mark TextField
//TextField
#define TTL_TEXTFIELD_BORDER_INACTIVE_COLOR @"DCDCDC"

#pragma mark Button
//Button
#define TTL_BUTTON_INACTIVE_BACKGROUND_GRADIENT_LIGHT_COLOR @"CECECE"
#define TTL_BUTTON_INACTIVE_BACKGROUND_GRADIENT_DARK_COLOR @"9B9B9B"
#define TTL_BUTTON_INACTIVE_BORDER_COLOR @"CECECE"

#pragma mark Switch
//Switch
#define TTL_SWITCH_INACTIVE_BACKGROUND_COLOR @"9B9B9B"

#pragma mark Unread Badge
//Unread Badge
#define TTL_UNREAD_BADGE_INACTIVE_BACKGROUND_COLOR @"9B9B9B"

#pragma mark SearchBar
//SearchBar
#define TTL_SEARCHBAR_BORDER_INACTIVE_COLOR @"DCDCDC"

#pragma mark Chat Room Page
//Chat Room Page
#define TTL_LEFT_BUBBLE_BACKGROUND_COLOR @"FFFFFF"
#define TTL_LEFT_BUBBLE_QUOTE_BACKGROUND_COLOR @"F3F3F3"
#define TTL_SYSTEM_MESSAGE_BACKGROUND_COLOR @"FFFFFF"
#define TTL_SYSTEM_MESSAGE_BACKGROUND_SHADOW_COLOR @"D9D9D9"
#define TTL_FILE_PROGRESS_BACKGROUND_COLOR @"FFFFFF"
#define TTL_DELETED_CHAT_ROOM_INFO_BACKGROUND_COLOR @"FFF4B1"
#define TTL_SEARCH_CONNECTION_LOST_BACKGROUND_COLOR @"FFF4B1"
#define TTL_CHAT_COMPOSER_BACKGROUND_COLOR @"FFFFFF"

#pragma mark - Component Font Size
//Component Font Size
#define TTL_TITLE_LABEL_FONTSIZE_STYLE 40.0f
#define TTL_NAVIGATION_BAR_TITLE_LABEL_FONTSIZE_STYLE 20.0f
#define TTL_NAVIGATION_BAR_BUTTON_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_FORM_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_FORM_DESCRIPTION_LABEL_FONTSIZE_STYLE 14.0f
#define TTL_FORM_ERROR_INFO_LABEL_FONTSIZE_STYLE 14.0f
#define TTL_FORM_TEXTFIELD_FONTSIZE_STYLE 16.0f
#define TTL_FORM_TEXTFIELD_PLACEHOLDER_FONTSIZE_STYLE 14.0f
#define TTL_CLICKABLE_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_CLICKABLE_DESTRUCTIVE_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_BUTTON_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_INFO_LABEL_TITLE_FONTSIZE_STYLE 24.0f
#define TTL_INFO_LABEL_SUBTITLE_FONTSIZE_STYLE 18.0f
#define TTL_INFO_LABEL_BODY_FONTSIZE_STYLE 14.0f
#define TTL_KEYBOARD_ACCESSORY_LABEL_FONTSIZE_STYLE 14.0f
#define TTL_POPUP_LOADING_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_SEARCH_CONNECTION_LOST_TITLE_FONTSIZE_STYLE 16.0f
#define TTL_SEARCH_CONNECTION_LOST_DESCRIPTION_FONTSIZE_STYLE 14.0f
#define TTL_UNREAD_BADGE_LABEL_FONTSIZE_STYLE 11.0f
#define TTL_DEFAULT_ROOM_AVATAR_SMALL_LABEL_FONTSIZE_STYLE 12.0f
#define TTL_DEFAULT_ROOM_AVATAR_MEDIUM_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_DEFAULT_ROOM_AVATAR_LARGE_LABEL_FONTSIZE_STYLE 24.0f
#define TTL_DEFAULT_ROOM_AVATAR_EXTRA_LARGE_LABEL_FONTSIZE_STYLE 32.0f

#pragma mark - SearchBar
//SearchBar
#define TTL_SEARCHBAR_TEXT_FONTSIZE_STYLE 14.0f
#define TTL_SEARCHBAR_TEXT_PLACEHOLDER_FONTSIZE_STYLE 14.0f
#define TTL_SEARCHBAR_TEXT_CANCEL_BUTTON_FONTSIZE_STYLE 17.0f

#pragma mark Popup Dialog/View
//Popup Dialog/View
#define TTL_POPUP_DIALOG_TITLE_FONTSIZE_STYLE 16.0f
#define TTL_POPUP_DIALOG_BODY_FONTSIZE_STYLE 14.0f
#define TTL_POPUP_DIALOG_BUTTON_TEXT_PRIMARY_SUCCESS_FONTSIZE_STYLE 12.0f
#define TTL_POPUP_DIALOG_BUTTON_TEXT_SECONDARY_FONTSIZE_STYLE 12.0f
#define TTL_POPUP_DIALOG_SECONDARY_BACKGROUND_COLOR @"FFFFFF"

#pragma mark Action Sheet
//Action Sheet
#define TTL_ACTION_SHEET_DEFAULT_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_ACTION_SHEET_DESTRUCTIVE_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_ACTION_SHEET_CANCEL_BUTTON_LABEL_FONTSIZE_STYLE 20.0f

#pragma mark TableView
//TableView
#define TTL_TABLEVIEW_SECTION_HEADER_LABEL_FONTSIZE_STYLE 11.0f

#pragma mark Contact List
//Contact List
#define TTL_CONTACT_LIST_NAME_FONTSIZE_STYLE 14.0f
#define TTL_CONTACT_LIST_NAME_HIGHLIGHTED_FONTSIZE_STYLE 14.0f
#define TTL_CONTACT_LIST_USERNAME_FONTSIZE_STYLE 12.0f

#pragma mark Media
//Media
#define TTL_MEDIA_LIST_INFO_LABEL_FONTSIZE_STYLE 12.0f

#pragma mark Room List Page
//Room List Page
#define TTL_ROOM_LIST_NAME_FONTSIZE_STYLE 16.0f
#define TTL_ROOM_LIST_NAME_HIGHLIGHTED_FONTSIZE_STYLE 16.0f
#define TTL_ROOM_LIST_MESSAGE_FONTSIZE_STYLE 14.0f
#define TTL_ROOM_LIST_MESSAGE_HIGHLIGHTED_FONTSIZE_STYLE 14.0f
#define TTL_ROOM_LIST_TIME_FONTSIZE_STYLE 11.0f
#define TTL_GROUP_ROOM_LIST_SENDER_NAME_FONTSIZE_STYLE 14.0f
#define TTL_ROOM_LIST_UNREAD_BADGE_LABEL_FONTSIZE_STYLE 11.0f

#pragma mark New Chat Page
//New Chat Page
#define TTL_NEW_CHAT_MENU_LABEL_FONTSIZE_STYLE 16.0f

#pragma mark Chat Profile Page
//Chat Profile Page
#define TTL_CHAT_PROFILE_ROOM_NAME_LABEL_FONTSIZE_STYLE 20.0f
#define TTL_CHAT_PROFILE_MENU_LABEL_FONTSIZE_STYLE 14.0f
#define TTL_CHAT_PROFILE_MENU_DESTRUCTIVE_LABEL_FONTSIZE_STYLE 14.0f

#pragma mark New Contact Page
//New Contact Page
#define TTL_SEARCH_NEW_CONTACT_RESULT_NAME_FONTSIZE_STYLE 20.0f
#define TTL_SEARCH_NEW_CONTACT_RESULT_USERNAME_FONTSIZE_STYLE 14.0f

#pragma mark Gallery Picker Page
//Gallery Picker Page
#define TTL_ALBUM_NAME_LABEL_FONTSIZE_STYLE 18.0f
#define TTL_ALBUM_COUNT_LABEL_FONTSIZE_STYLE 12.0f
#define TTL_GALLERY_PICKER_CANCEL_BUTTON_FONTSIZE_STYLE 14.0f
#define TTL_GALLERY_PICKER_CONTINUE_BUTTON_FONTSIZE_STYLE 14.0f

#pragma mark Chat Room Page
//Chat Room Page
#define TTL_CHAT_ROOM_NAME_LABEL_FONTSIZE_STYLE 18.0f
#define TTL_CHAT_ROOM_STATUS_LABEL_FONTSIZE_STYLE 13.0f
#define TTL_CHAT_COMPOSER_TEXTFIELD_FONTSIZE_STYLE 14.0f
#define TTL_CHAT_COMPOSER_TEXTFIELD_PLACEHOLDER_FONTSIZE_STYLE 14.0f
#define TTL_CUSTOM_KEYBOARD_ITEM_LABEL_FONTSIZE_STYLE 14.0f
#define TTL_QUOTE_LAYOUT_TITLE_LABEL_FONTSIZE_STYLE 12.0f
#define TTL_QUOTE_LAYOUT_CONTENT_LABEL_FONTSIZE_STYLE 12.0f
#define TTL_RIGHT_BUBBLE_MESSAGE_BODY_FONTSIZE_STYLE 16.0f
#define TTL_LEFT_BUBBLE_MESSAGE_BODY_FONTSIZE_STYLE 16.0f
#define TTL_RIGHT_BUBBLE_MESSAGE_BODY_URL_FONTSIZE_STYLE 16.0f
#define TTL_LEFT_BUBBLE_MESSAGE_BODY_URL_FONTSIZE_STYLE 16.0f
#define TTL_RIGHT_BUBBLE_MESSAGE_BODY_URL_HIGHLIGHTED_FONTSIZE_STYLE 16.0f
#define TTL_LEFT_BUBBLE_MESSAGE_BODY_URL_HIGHLIGHTED_FONTSIZE_STYLE 16.0f
#define TTL_RIGHT_BUBBLE_DELETED_MESSAGE_BODY_FONTSIZE_STYLE 16.0f
#define TTL_LEFT_BUBBLE_DELETED_MESSAGE_BODY_FONTSIZE_STYLE 16.0f
#define TTL_RIGHT_BUBBLE_QUOTE_TITLE_FONTSIZE_STYLE 12.0f
#define TTL_LEFT_BUBBLE_QUOTE_TITLE_FONTSIZE_STYLE 12.0f
#define TTL_RIGHT_BUBBLE_QUOTE_CONTENT_FONTSIZE_STYLE 12.0f
#define TTL_LEFT_BUBBLE_QUOTE_CONTENT_FONTSIZE_STYLE 12.0f
#define TTL_RIGHT_FILE_BUBBLE_NAME_FONTSIZE_STYLE 12.0f
#define TTL_LEFT_FILE_BUBBLE_NAME_FONTSIZE_STYLE 12.0f
#define TTL_RIGHT_FILE_BUBBLE_INFO_FONTSIZE_STYLE 12.0f
#define TTL_LEFT_FILE_BUBBLE_INFO_FONTSIZE_STYLE 12.0f
#define TTL_LEFT_BUBBLE_SENDER_NAME_FONTSIZE_STYLE 14.0f
#define TTL_BUBBLE_MESSAGE_STATUS_FONTSIZE_STYLE 12.0f
#define TTL_BUBBLE_MEDIA_INFO_FONTSIZE_STYLE 12.0f
#define TTL_SYSTEM_MESSAGE_BODY_FONTSIZE_STYLE 11.0f
#define TTL_CHAT_ROOM_UNREAD_BADGE_FONTSIZE_STYLE 11.0f
#define TTL_UNREAD_MESSAGE_IDENTIFIER_FONTSIZE_STYLE 12.0f
#define TTL_UNREAD_MESSAGE_BUTTON_LABEL_FONTSIZE_STYLE 12.0f
#define TTL_DELETED_CHAT_ROOM_INFO_TITLE_FONTSIZE_STYLE 16.0f
#define TTL_DELETED_CHAT_ROOM_INFO_CONTENT_FONTSIZE_STYLE 14.0f

#pragma mark Location Picker Page
//Location Picker Page
#define TTL_LOCATION_PICKER_TEXTFIELD_FONTSIZE_STYLE 13.0f
#define TTL_LOCATION_PICKER_TEXTFIELD_PLACEHOLDER_FONTSIZE_STYLE 13.0f
#define TTL_LOCATION_PICKER_TEXTFIELD_CLEAR_BUTTON_FONTSIZE_STYLE 10.0f
#define TTL_LOCATION_PICKER_SEARCH_RESULT_FONTSIZE_STYLE 13.0f
#define TTL_LOCATION_PICKER_ADDRESS_FONTSIZE_STYLE 12.0f
#define TTL_LOCATION_PICKER_ADDRESS_PLACEHOLDER_FONTSIZE_STYLE 12.0f
#define TTL_LOCATION_PICKER_SEND_LOCATION_BUTTON_FONTSIZE_STYLE 12.0f

#pragma mark Send Media Preview Page
//Send Media Preview Page
#define TTL_MEDIA_PREVIEW_CANCEL_BUTTON_FONTSIZE_STYLE 16.0f
#define TTL_MEDIA_PREVIEW_ITEM_COUNT_FONTSIZE_STYLE 16.0f
#define TTL_MEDIA_PREVIEW_CAPTION_FONTSIZE_STYLE 14.0f
#define TTL_MEDIA_PREVIEW_CAPTION_PLACEHOLDER_FONTSIZE_STYLE 14.0f
#define TTL_MEDIA_PREVIEW_CAPTION_LETTER_COUNT_FONTSIZE_STYLE 10.0f
#define TTL_MEDIA_PREVIEW_SEND_BUTTON_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_MEDIA_PREVIEW_WARNING_TITLE_FONTSIZE_STYLE 14.0f
#define TTL_MEDIA_PREVIEW_WARNING_BODY_FONTSIZE_STYLE 12.0f

#pragma mark Image Detail Preview Page
//Image Detail Preview Page
#define TTL_IMAGE_DETAIL_SENDER_NAME_FONTSIZE_STYLE 14.0f
#define TTL_IMAGE_DETAIL_MESSAGE_STATUS_FONTSIZE_STYLE 12.0f
#define TTL_IMAGE_DETAIL_CAPTION_FONTSIZE_STYLE 15.0f

#pragma mark Custom Notification Page (In App Notification)
//Custom Notification Page (In App Notification)
#define TTL_CUSTOM_NOTIFICATION_TITLE_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_CUSTOM_NOTIFICATION_CONTENT_LABEL_FONTSIZE_STYLE 14.0f

#pragma mark - Group Chat
//Group Chat
#define TTL_SELECTED_MEMBER_LIST_NAME_FONTSIZE_STYLE 11.0f
#define TTL_GROUP_MEMBER_COUNT_FONTSIZE_STYLE 16.0f

#pragma mark Country Picker
//Country Picker Page
#define TTL_COUNTRY_PICKER_LABEL_FONTSIZE_STYLE 16.0f

#pragma mark Login Verification (OTP)
//Login Verification (OTP) Page
#define TTL_LOGIN_VERIFICATION_INFO_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_LOGIN_VERIFICATION_PHONE_NUMBER_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_LOGIN_VERIFICATION_STATUS_COUNTDOWN_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_LOGIN_VERIFICATION_STATUS_LOADING_LABEL_FONTSIZE_STYLE 16.0f
#define TTL_LOGIN_VERIFICATION_STATUS_SUCCESS_LABEL_FONTSIZE_STYLE 16.0f



#pragma mark Topic List
//Topic List Page
#define TTL_TOPIC_LIST_LABEL_FONTSIZE_STYLE 16.0f

#endif /* TTLStyle_h */
